### ISSUE TITLE
壁纸加载不出来

### ISSUE THREAD

**Issue by Gugoole** [JuniperPhoton/MyerSplash.UWP#15]
壁纸一直加载不了，开了ss也不行，看了ms store的评论貌似很多人遇到了这个问题，如果这个项目还在维护的话，希望尽快处理这个bug

**Comment by JuniperPhoton** [comment]
最好确认一下一个事情：

开 SS 不一定能让 UWP apps 科学上网，试试 Twitter 和 Edge 是否能用，如果不行，请自行 Google。

**Comment by Gugoole** [comment]
貌似和ss没有关系，但是图片加载确实太慢慢慢慢慢慢慢慢了，希望优化这个问题
