### ISSUE TITLE
Daily recommendation is empty

### ISSUE THREAD

**Issue by Leonsama** [JuniperPhoton/MyerSplash.UWP#175]
Since January 1, 2022, the daily recommendation is empty, and everything else is normal. It should not be caused by the network.

**Comment by JuniperPhoton** [comment]
Thanks for your support. Highlights is no longer supported and updated since 2022. If you are using iOS, iPadOS and macOS , you should receive the new update to MyerSplash, and the Android version is comming soon.

However, the Windows version is no longer maintained.
