### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by EcstasyAwesome** [JuniperPhoton/MyerSplash.UWP#27]
Hi! I can't download any picture and open the wallpapers folder from the app. I already reinstalled the app and check all permissions in the settings. It happened after some update. What could it be?
Thanks!

[Error log](https://github.com/JuniperPhoton/MyerSplash.UWP/files/3039925/ErrorLog.915.log)

![error](https://user-images.githubusercontent.com/29777687/55498050-53348e80-564b-11e9-93a3-a1446bf012ac.png)

**Comment by JuniperPhoton** [comment]
Sorry for my delayed replay.

Please check the permission by these steps:

1. Go to `Pictures/ dir`, and find whether this is a folder named `MyerSplash`;
2. If so, open it and try to create a new file or open the existed file;
3. If it still do, try to open the `Properties` panel of `Pictures/MyerSplash`, and checkout the permissions on Security tab. The current user should have permission to access the folder.

![image](https://user-images.githubusercontent.com/7578386/56046543-13218a00-5d76-11e9-9c6b-f79b89e07748.png)

**Comment by EcstasyAwesome** [comment]
No problem)
That was the first thing what i did. All users and groups already have full access to the folder. I didn't make any changes to my computer. I think, it appeared after updating the program.
![temp](https://user-images.githubusercontent.com/29777687/56051016-1147ce80-5d56-11e9-8b3e-2edf09b1713b.jpg)

**Comment by JuniperPhoton** [comment]
Can you try deleting the MyerSplash folder and re-installing the app?

**Comment by JuniperPhoton** [comment]
Also, please check those things:

1. Have you moved the location of Pictures library?
2. Have you changed the location where UWP apps will be installed?

I am not sure why this happens but it's worth trying to setting the settings above to default.

**Comment by EcstasyAwesome** [comment]
After deleting the folder and re-installing the app, the programm can't create a new folder in Pictures library. I changed Pictures library to default location and it not helped(
1.  Yes, 3 years ago, when i first instaled win10 (2-3 months ago everything worked fine)
2.  No

**Comment by EcstasyAwesome** [comment]
Finally! I solved this issue. I don't know why, but my pictures library was empty. I configured those libraries in the past, when windows 10 was installed. I included my pictures folder in the windows pictures library and it worked.

Instructions.
[https://winaero.com/blog/include-folder-library-windows-10/](url)
