### ISSUE TITLE
The wallpaper of two pc updates are out of sync

### ISSUE THREAD

**Issue by gz222** [JuniperPhoton/MyerSplash.UWP#30]
The wallpaper of two pc updates are out of sync. The Internet is a little slow but basically fine. Two computers, sometimes A updates first, sometimes B updates first, can not keep the same wallpaper in time.

**Comment by JuniperPhoton** [comment]
Because the background tasks are scheduled by Windows, I can not guarantee they will sync. BTW The background tasks registered by MyerSplash should be triggered every 4 hours in a day.
