### ISSUE TITLE
Tile

### ISSUE THREAD

**Issue by EcstasyAwesome** [JuniperPhoton/MyerSplash.UWP#32]
The picture is bigger than tile.

![2019-09-19 144939](https://user-images.githubusercontent.com/29777687/65241845-4c141680-daed-11e9-9f8e-d3274d861c18.jpg)

**Comment by JuniperPhoton** [comment]
This is a bug in garbage Windows 10 1903. And it has not been fixed in 19H2 yet.

Please report this issue to Microsoft.
